#!/bin/sh
# gftops -- translate gf to PostScript
# $Id: gftops 151 1995-05-06 14:33:31Z ohl $
name=$1
dpi=300
trap "rm -f ${name}.${dpi}pk $name.*.pbm" 0 1 2 3 15
gftopk ${name}.${dpi}gf
for c in \
  `pktype ${name}.${dpi}pk | sed -n 's/^.*Character = \([0-9]*\).*$/\1/p'`
do
  pktopbm ${name}.${dpi}pk -c $c $name.$c.pbm 2>/dev/null
  pnmtops -noturn -nocenter -dpi 300 -scale 0.25 < $name.$c.pbm > $name.$c
done
exit 0
